### ISSUE TITLE
Backend Not Starting Up

### ISSUE THREAD

**Issue by gizlonk** [arcolife/sarjitsu#9]
Hi, Creating this as issue not resolved in the last query.

backend is not starting up. I tried applying the fix from last time, but now Im getting a new problem - I cannot remove or install packages inside the backend container, permission denied:

```[flask@cfc65e5df91c src]$ pip3 uninstall requests
Uninstalling requests-2.18.1:
  /usr/lib/python3.5/site-packages/requests-2.18.1.dist-info/DESCRIPTION.rst
  /usr/lib/python3.5/site-packages/requests-2.18.1.dist-info/INSTALLER
  /usr/lib/python3.5/site-packages/requests-2.18.1.dist-info/METADATA
  /usr/lib/python3.5/site-packages/requests-2.18.1.dist-info/RECORD
  /usr/lib/python3.5/site-packages/requests-2.18.1.dist-info/WHEEL
  /usr/lib/python3.5/site-packages/requests-2.18.1.dist-info/metadata.json
  /usr/lib/python3.5/site-packages/requests-2.18.1.dist-info/top_level.txt
  /usr/lib/python3.5/site-packages/requests/__init__.py
  /usr/lib/python3.5/site-packages/requests/__pycache__/__init__.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/__version__.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/_internal_utils.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/adapters.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/api.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/auth.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/certs.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/compat.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/cookies.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/exceptions.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/help.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/hooks.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/models.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/packages.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/sessions.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/status_codes.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/structures.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__pycache__/utils.cpython-35.pyc
  /usr/lib/python3.5/site-packages/requests/__version__.py
  /usr/lib/python3.5/site-packages/requests/_internal_utils.py
  /usr/lib/python3.5/site-packages/requests/adapters.py
  /usr/lib/python3.5/site-packages/requests/api.py
  /usr/lib/python3.5/site-packages/requests/auth.py
  /usr/lib/python3.5/site-packages/requests/certs.py
  /usr/lib/python3.5/site-packages/requests/compat.py
  /usr/lib/python3.5/site-packages/requests/cookies.py
  /usr/lib/python3.5/site-packages/requests/exceptions.py
  /usr/lib/python3.5/site-packages/requests/help.py
  /usr/lib/python3.5/site-packages/requests/hooks.py
  /usr/lib/python3.5/site-packages/requests/models.py
  /usr/lib/python3.5/site-packages/requests/packages.py
  /usr/lib/python3.5/site-packages/requests/sessions.py
  /usr/lib/python3.5/site-packages/requests/status_codes.py
  /usr/lib/python3.5/site-packages/requests/structures.py
  /usr/lib/python3.5/site-packages/requests/utils.py
Proceed (y/n)? y
Exception:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/shutil.py", line 544, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.5/site-packages/requests-2.18.1.dist-info/DESCRIPTION.rst' -> '/tmp/pip-3xfm4ulm-uninstall/usr/lib/python3.5/site-packages/requests-2.18.1.dist-info/DESCRIPTION.rst'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.5/site-packages/pip/commands/uninstall.py", line 76, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/usr/lib/python3.5/site-packages/pip/req/req_set.py", line 336, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/usr/lib/python3.5/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python3.5/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/lib/python3.5/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib64/python3.5/shutil.py", line 559, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.5/site-packages/requests-2.18.1.dist-info/DESCRIPTION.rst'
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Your assistance would be greatly appreciated.

**Comment by arcolife** [comment]
So the latest master branch code, works with openshift (non-root containers) as well as docker-compose. Problem with usage of pip that way is https://github.com/arcolife/sarjitsu/blob/master/lib/backend/Dockerfile#L75

The user that you get after logging in to container now, is not root, It's flask (ref: https://github.com/arcolife/sarjitsu/blob/master/lib/backend/conf/passwd.template#L14 )

The solution to this would be to add a --user flag in front of flask, but since the process has already started inside the container, that wouldn't solve your issue. And if you kill the flask wsgi process, it would kill the container.

I see that it works with the versions I've put in the PR for https://github.com/arcolife/sarjitsu/issues/8

Also, please don't open a new issue with same context. I'd appreciate comments on same thread. :-) I'll reopen for sure, if the issue persists.
